@copier @scaffolding @docker @docker-compose
Feature: Docker Compose Support

  To simplify the orchestration of multiple services
  As a developer
  I want a standard docker-compose.yml file generated by default when Docker is selected

  Scenario: Docker Compose file is generated by default when Docker is selected
    Given a clean temporary directory for "docker/compose" tests
    And a project was generated with container runtime "docker"
    Then the "project/docker-compose.yml" file should exist
    And the docker-compose project name should match the directory name
    And the file "project/docker-compose.yml" should contain "networks:"
    And the file "project/docker-compose.yml" should contain "# include:"
    And the file "project/docker-compose.yml" should contain "#   - your_service/docker-compose.yml"

  Scenario: Docker Compose file is NOT generated when explicitly disabled
    Given a clean temporary directory for "docker/compose-disabled" tests
    When the copier command is executed with:
      | container_runtime | docker |
      | use_docker_compose | false |
    Then the "project/docker-compose.yml" file should NOT exist

  Scenario: Docker Compose file is NOT generated when Podman is selected
    Given a clean temporary directory for "docker/compose-podman" tests
    And a project was generated with container runtime "podman"
    Then the "project/docker-compose.yml" file should NOT exist
