---
spec:
  inputs:
    TASK_DEVSECOPS_RELEASE_ENABLED:
      default: true
      type: boolean
      description: "Enable the DevSecOps release task."
    RUN_FEEDBACK_SCHEDULE:
      default: true
      type: boolean
      description: "Feedback schedule configuration."
---
image: registry.gitlab.com/digital-commons/devsecops/the-devsecops-toolbox:17.2.1

variables:
  TASK_DEVSECOPS_RELEASE_ENABLED: $[[ inputs.TASK_DEVSECOPS_RELEASE_ENABLED ]]
  RUN_FEEDBACK_SCHEDULE: $[[ inputs.RUN_FEEDBACK_SCHEDULE ]]

include:
  - local: .config/gitlab/ci/before_script.yml
  - local: .config/gitlab/ci/cache.yml
  - local: .config/gitlab/ci/services.yml
  - local: .config/gitlab/ci/stages.yml
  - local: .config/gitlab/ci/tags.yml
  - local: .config/gitlab/ci/variables.yml
  - local: .config/gitlab/ci/workflow.yml

  - local: .config/gitlab/ci/devsecops/plan.yml
  - local: .config/gitlab/ci/devsecops/code.yml
  - local: .config/gitlab/ci/devsecops/build.yml
  - local: .config/gitlab/ci/devsecops/test.yml
  - local: .config/gitlab/ci/devsecops/release.yml
  - local: .config/gitlab/ci/devsecops/deploy.yml
  - local: .config/gitlab/ci/devsecops/operate.yml
  - local: .config/gitlab/ci/devsecops/monitor.yml
  - local: .config/gitlab/ci/devsecops/feedback.yml
