---
# Project-specific Megalinter configuration
# This file extends the base configuration provided by the template.
# You can override or add settings here.

EXTENDS: .config/megalinter/config.base.yml
