#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

TASK_GLAB_PROJECT_TOKEN_NAME="${TASK_GLAB_COMMITIZEN_TOKEN_NAME:-TASK_COMMITIZEN_TOKEN}" \
  TASK_GLAB_PROJECT_TOKEN_PROTECTED="${TASK_GLAB_COMMITIZEN_TOKEN_PROTECTED:-true}" \
  TASK_GLAB_PROJECT_TOKEN_FORCE="${TASK_GLAB_COMMITIZEN_TOKEN_FORCE:-false}" \
  TASK_GLAB_PROJECT_TOKEN_ACCESS_LEVEL="40" \
  TASK_GLAB_PROJECT_TOKEN_SCOPES="api,write_repository" \
  TASK_GLAB_PROJECT_TOKEN_LABEL="Commitizen" \
  bash "${SCRIPT_DIR}/project-token.sh"
