exclude = [
  'file://*',
  'file://charts/',
  'http://127.0.0.1',
  'http://gitlab',
  'http://localhost',
  'http://proxy',
  'https://dl.k8s.io/release/',
  'https://docker:8001',
  'https://localhost',
  'https://tidelift.com/funding/github/npm/parse-function',
  'tcp://*'
]

exclude_path = [
  '(^|/)package-lock\.json$'
]
